config {
  type: "table",
  schema: "dataform",
  name: "t_meals",
  assertions: {
    nonNull: ["meal_id", "meal_name", "calories"],
    rowConditions: [
      'execution_date < "2022-08-01"',
      'meal_name LIKE "S%"'
    ]
  }
}


SELECT DISTINCT meal_id,
                meal_name,
                calories,
                '${dataform.projectConfig.vars.execution_date}' AS execution_date

                FROM ${ref("meals")}
